### ISSUE TITLE
normal_ext.dynamic rendertypes do not obey ingame transparency modifiers

### ISSUE THREAD

**Issue by DoctorAnsem** [SleepKiller/shaderpatch#103]
It's self-explanatory. If a unit, with a cloth that has a dynamic rendertype, uses an invisibility weapon, the cloth will remain visible even to enemies.

**Comment by SleepKiller** [comment]
Ohh, thanks for letting me know. Almost sounds like this could be related to #70. (Which would be nice to be able to fix them both at the same time.)
