### ISSUE TITLE
Terrain shader actually is affected by 'light brightness rescaling'

### ISSUE THREAD

**Issue by auri0n** [SleepKiller/shaderpatch#114]
I mistakenly said that it was the only shader _not_ affected by SWBF2's brightness rescaling >.< Sorry about that. Hopefully it's an easy fix for v1.4, although I've heard bad things about the terrain shader.

**Comment by SleepKiller** [comment]
As far as I have been able to tell the game uses the perpixel/normalmapping shaders for terrain lighting when Lighting quality is set to Medium or High. Which probably makes this the same issue as #115 so I'll close this issue and we can track this there as well.

Side Note: On Low Lighting quality terrain lighting is calculated using the same function as normal surfaces so there should be no issue there.
