### ISSUE TITLE
PBR "basic" subtype (and its successor) has broken

### ISSUE THREAD

**Issue by DoctorAnsem** [SleepKiller/shaderpatch#127]
It's not specific to the old pbr.basic rendertype - simply put, _any_ PBR material that sets the new `NoMetallicRoughnessMap` flag true is always drawn fully reflective as if it had a Roughness value of 0, despite what the value actually is. (changing it doesn't do anything)

**Comment by SleepKiller** [comment]
Thanks for testing and reporting it! I'll be sure to look into it as soon as possible.

**Comment by SleepKiller** [comment]
[v1.4.0-preview.8](https://github.com/SleepKiller/shaderpatch/releases/tag/v1.4.0-preview.8) contains a fix for this. Let me know if you come across any other issues like it!
