### ISSUE TITLE
When Effects System is active windows can be too perfect.

### ISSUE THREAD

**Issue by SleepKiller** [SleepKiller/shaderpatch#22]
I haven't been able to replicate this but it is fairly serious. Any info (such as the GPU you're using) from anyone encountering this would be much appreciated.

![star_wars_battlefront_ii_8_1_2018_1_07_51_pm](https://user-images.githubusercontent.com/5582558/43557590-632df090-9659-11e8-9028-86e378d06cc0.png)

**Comment by SleepKiller** [comment]
Thanks to @Calrissian97 who spent a fair bit of his time helping me (so big props to him) work through the usual suspects I now know that it is unlikely to be any of usual suspects.

Things that don't seem to be causing it,
* GPU Type - Calrissian97 and I each tested on the same kind of Intel GPU. He had the bug while I didn't.
* GPU Driver - Calrissian97 tested two separate Intel drivers and got the bug in both cases. I tested one of the ones he did and didn't get the bug.

It is a very strange one, there must be something specific with my or his environment that we're as yet unaware of that is causing it.

**Comment by Calrissian97** [comment]
Note: Turning shadows off in the in-game settings is a temporary workaround.

**Comment by SleepKiller** [comment]
767fc0127676ab28f34697066df54ee9691417ed may have had a (positive?) effect on this. Under the way I'm able to reproduce it transparent objects are now drawn correctly but shadows are still missing. Nonetheless progress... maybe.
