### ISSUE TITLE
Death Star hangar doors have lighting problems when HDR is enabled

### ISSUE THREAD

**Issue by auri0n** [SleepKiller/shaderpatch#31]
https://i.imgur.com/202Ehyq.mp4

Apologies for the choppy video, but hopefully it's good enough lol. As far as I know, those doors are the only thing in the game that still glitch out when HDR rendering is turned on. Aside from this, there are only two other bugs I'm aware of - I'll post the others in a bit. Thanks for reading!

**Comment by SleepKiller** [comment]
SP no longer tries make have regular normal mapped materials render correctly, instead the quality of the postprocessing without HDR rendering has been improved in [v1.0.0](https://github.com/SleepKiller/shaderpatch/releases/tag/v1.0.0-rc.0). 

So I'm going to close this particular issue, thanks for reporting it though!
