### ISSUE TITLE
Terrain colors are all sorts of wrong

### ISSUE THREAD

**Issue by DoctorAnsem** [SleepKiller/shaderpatch#33]
Apologies if this isn't the correct place for this and/or it's been reported before, but I don't know what would be a better choice at this time. I'm in a stalemate with an issue that has been a long standing one even in the stock terrain shader (is what I assume at any rate) that causes terrain colors to go way off the target in BFII whenever the Lighting Quality option is set to 'High'. It also only affects the Near Scene, the Far Scene is shaded with the right colors. 

I was thinking by configuring the my maps to use HDR from the shader patch, I could bypass the problem but turns out it only makes it worse. I've made a comparison image to demonstrate what I mean - top left image is the one with all the colors correctly applied.

https://i.imgur.com/hujyUF3.jpg

As you can see, any configuration that isn't the stock shader with Medium Quality lights is fundamentally incorrect and it's frustrating beyond imagination because there's no real workaround. High Quality darkens the near scene for whatever reason, and HDR just outright destroys the color scheme while still suffering from the same problem as the stock shader. (Also, HDR doesn't handle sky fog very well? Why did it turn pitch black with no fade lol)

Again, sorry if this isn't the right place. I'm just hoping in the future this color issue could be exterminated so that we can make our maps actually look like how we design them, and it seems like Shaderpatch is the future. I've recently started to get familiar with the material system and so far I like the results.

**Comment by DoctorAnsem** [comment]
It's been a while and something regarding this popped up so I'm gonna make a little bit of an update.

So while this bug no longer ruins the 'stock' terrain lighting (bit of a silly way to phrase it, yeah), the HDR terrains are still misbehaving. I'm not even sure what is happening exactly, but the key point is that with the light quality at 'High', Near Scene terrain becomes a bit darker and makes it mismatch with the Far Scene. So there's the classic. The next part gets tricky though. I think I'll rather [show](https://drive.google.com/open?id=1z741XKFM3lurnAbpjjMo2Yy50aqe0nWn).

So the black band. I don't have the slightest clue what that is. It's in the intersection of near and far scenes but that's about as much as I can tell. It could be something to do with sky fog because I've set it to range from 160 (the point where near scene also starts to fade out) to 600 but I don't know for sure.

Also to clarify, the video actually shows that the terrain color would be correct in near scene and too bright in far scene, but this isn't the case; I manually adjusted the prop diffuse colors to match the near scene.

**Comment by SleepKiller** [comment]
Just cleaning out open issues that I'm unsure if are still problems or not. As always feel free to reopen this or a new issue if this still requires addressing in someway.

As an aside though one of the fixes in v1.3.3 should hopefully have solved the near scene far scene HDR mismatch. Or at the very least helped with it.
