### ISSUE TITLE
normal_ext.specular has funky shadow interaction

### ISSUE THREAD

**Issue by DoctorAnsem** [SleepKiller/shaderpatch#39]
This seems like such a blatantly obvious phenomenon so it's probably been mentioned already, but regardless. It turns out if the specular spot is being cast onto a shadowed surface, the color gets massively subtracted so it casts darkness instead.

![specularblack](https://user-images.githubusercontent.com/45246040/50377293-57501980-0623-11e9-8f9d-5fd139e1195b.png)

EDIT: You know something? It's not just the specular extension that has weird stuff happen with shadows. It seems on a normal_ext material without the specular extension, all shadows that are cast on the surface become pitch black. I definitely remember reading about this one before so maybe I didn't need to report this after all, but what's done is done.

**Comment by SleepKiller** [comment]
I did think I had fixed this but it must have only been in some circumstances. Thanks for letting me know, I'll have to look into it. 

> I definitely remember reading about this one before so maybe I didn't need to report this after all, but what's done is done.

If there isn't an issue open for it then always feel free to assume I either don't know about it or I have forgotten about it.

**Comment by SleepKiller** [comment]
[v1.0.0](https://github.com/SleepKiller/shaderpatch/releases/tag/v1.0.0-rc.0) should've resolve this. Let me know if it hasn't
