### ISSUE TITLE
Smoke from damaged snowspeeders/ships looks blocky

### ISSUE THREAD

**Issue by auri0n** [SleepKiller/shaderpatch#42]
I just realized that I never reported that third issue I had mentioned a while back ._. 

https://i.imgur.com/gp8Y5Ps.mp4

This problem occurs regardless of effects being enabled.

**Comment by SleepKiller** [comment]
Finally (6 month response time, I'm such a great developer) investigated this and it looks like this actually just down to the particle effect as it happens on the stock game as well. Let me know if I'm missing something though.
