### ISSUE TITLE
material_munge crashes, so does game

### ISSUE THREAD

**Issue by DoctorAnsem** [SleepKiller/shaderpatch#48]
`Material_munge` will crash with the "stopped working" message when it's editing models. It doesn't report any errors so I couldn't tell which model it is, but it worked in the previous version and I think I've properly updated all textures to line up with the new formatting so I'm not sure what's up. The game also crashes when it's loading the map, but no error messsages there either. It only ever loads up some of the textures, and it loads the effects config but then it goes kaput.

Edit: so apparently the game crashing might not even be related to the same issue. I successfully munged another map but it also crashes on the load screen. This time it did leave an error message, but...

`[ERROR]   19:13:44 Unexpected volume resource magic number!`

Wtf is that supposed to even mean? xd

**Comment by SleepKiller** [comment]
The error message indicates that there is still some files munged using old versions of the tools being packed into your lvls. Cleaning out your munged files should fix the problem.

This `material_munge` crash could be the root of your other problems. Do you have any idea which model it crashes on?

**Comment by DoctorAnsem** [comment]
Oh, derp. Yeah I thought I had cleaned up the munged files, but apparently not. That's one down.

Unfortunately, `material_munge `doesn't print out which model it is trying to edit when it crashes. It just garbles up the log.

`Editing bes2_prop_interior_door.model for Shader Patch...
EditingMunging (for Shader Patch) chamber01_emissive.tga
`
So essentially it's trying to do something to some model and then crashes and moves on to the textures. Curiously enough, though, just now when I re-munged without changing any source files, I got another strange .req error in the munge report. What's even more odd is that the textures it was trying to munge should have been already munged before, I didn't change them in between. The error message is as follows:
`Error occured while packing "bes2.req"
   Expected "ucft" but found "".`
I could guess that the .req error might be a result of `material_munge `crashing and not wrapping things up properly, but it's worth mentioning in case it's not.

**Comment by DoctorAnsem** [comment]
Oh my god... I just figured out why `material_munge` crashes and the reason is that I am Doctor Idiot and nobody ever told me about it.

In other words, there was a model that had an invalid slot 1 texture specified for rendertype 27, somewhere down the line I had written garbage in it and it was pointing to a texture that doesn't exist. Even the stock munge tools never pointed this out so I was blissfully ignorant about it lmao. Strange that the previous versions of `material_munge` didn't crash because of this, though.

I suppose that's a good suggestion for an improvement, and/or a feature request: make `material_munge` print warnings in the log when it finds missing textures like this xd

**Comment by SleepKiller** [comment]
`material_munge` now generates tangent space vectors (the things that make normal mapping work) for models, so it's a bit more sensitive to bad models now as it has to read a lot more of them.

But I agree that updating the error handling and logging of the tools to be more robust is a good idea.

**Comment by DoctorAnsem** [comment]
Oh yeah, I wanted to ask about the normal mapping too. So I noticed all my normal maps seem to be pointing the wrong way now, but I couldn't find consistency in it. What sort of standard does SP need now? Does it want inverted vectors or not? It wasn't just the Y vector that seemed to be wrong at times, there was inverted lighting on some X vectors too. (Maybe mirrored UVs are affecting it too? There were some parts of the same model that had normals facing correctly and then some parts that had them wrong.)

**Comment by SleepKiller** [comment]
It uses MikkTSpace (with the bitangent reconstructed in the pixel shader) now for custom materials. This is the same as the tangent space used by Blender, Unity & Unreal Engine (although iirc one of them reconstructs the bitangent in the vertex shader instead, which can matter when baking normal maps from models). Finding some normal map intended for use in one of them should give you your answer though, sorry I can't be more helpful. I just tested that it worked and everything was setup right I didn't pay much attention to the details of actually authoring normal maps. But do let me know if I've made a mistake somewhere and things aren't behaving how they should.

As for stock normal maps they should be the same as they've always been for the game without SP. Again let me know if this doesn't seem to be the case.

**Comment by DoctorAnsem** [comment]
I didn't get much useful info from the internet unfortunately, but after a little bit of brainstorming and testing, I've come to the conclusion that as of now, both stock and SP normal maps are correct when _no vectors are inverted_. As I said though, I think some of the models that use mirrored UVs to reflect a texture may be mirroring the normals as well and thus getting lit from the wrong direction, but I'll be sure to test that out a bit more before I go ahead and make that an actual claim.

**Comment by DoctorAnsem** [comment]
>  I think some of the models that use mirrored UVs to reflect a texture may be mirroring the normals as well and thus getting lit from the wrong direction

So interestingly enough, this seems to be the case, but only for the stock normals. After correcting the normal maps, SP materials are getting lit from the correct direction regardless of UV orientation so that's all good.

**Comment by SleepKiller** [comment]
Thanks, I'll have to compare my normal mapping code to Pandemic's again to try to see where I've gone wrong.
