### ISSUE TITLE
Shadow too intense

### ISSUE THREAD

**Issue by ShaderPatchedFox** [SleepKiller/shaderpatch#53]
So I'm finally joining GitHub to help that magnificent ShaderPatch to grow! 
-By the way I'm Fox from Discord/GT/Moddb- 

I noticed the "shadow bug" from issue 4 is back somehow: https://github.com/SleepKiller/shaderpatch/issues/4

It's almost like the shadow overwrite the terrain/prop(s) 's texture(s):

- **With ShaderPatch (v1.0.0-rc.2) installed:** 
https://i.imgur.com/PuSghY8.jpg

- **Without SP:**
https://i.imgur.com/52jWC1C.jpg
https://i.imgur.com/Xgak12b.jpg

I don't quite understand why it doesn't happen with _all_ the shadows. Like on the same map with SP installed some places are completely fine and others are just full black. 

- Would it be because some models use a shadow volume mesh and others use -hiresshadow in their .msh.option?    

- Could this be related to shadow intensity? Here's what I am talking about: https://imgur.com/qPOkx0W 
It's from Marth's website: https://www.aaron-gilbert.com/blog/2017/2/12/swbf2-lighting-tips

Anyway hope it helps, have a nice weekend!

**Comment by SleepKiller** [comment]
Thanks for opening an issue! It looks like it's probably something to do with the terrain shader, but I won't know for certain until I've tracked it down and fixed it.
