### ISSUE TITLE
Sunflares aren't rendering

### ISSUE THREAD

**Issue by auri0n** [SleepKiller/shaderpatch#61]
https://i.imgur.com/z7q5E3X.mp4

I think this issue has been present for all the RC builds. It looks like you're getting close to a final release, though, so congrats. I don't think there are any bugs that you aren't aware of at this point.

**Comment by SleepKiller** [comment]
Fixed by 6896f50caadf7bbccc994f49d2e3e0fb58e0489c and 09a262a8ac32175b4cff23bdc69096aa21c393e6 in v1.1 branch.
