### ISSUE TITLE
SP maps containing water crash the game

### ISSUE THREAD

**Issue by DoctorAnsem** [SleepKiller/shaderpatch#65]
It seems like there's still some problems with the way the water EnvFX is munged, as I have maps that contain water that crash the very moment there is supposed to be water in the active frame. No errors get logged.

**Comment by SleepKiller** [comment]
This is caused by SP's munge script leaving out `-platform PC` from it's invocation of `configmunge`. I've updated the [munge_world.bat](https://gist.github.com/SleepKiller/688ed49e361df1e7e6bf9687e92a6776#file-munge_world-bat-L114) with the fix.
