### ISSUE TITLE
Parallax Occlusion is very buggy

### ISSUE THREAD

**Issue by DoctorAnsem** [SleepKiller/shaderpatch#66]
[Seems like Parallax Occlusion might need some love,](https://drive.google.com/open?id=1L1RFBcttWcXxlv701r6r6Jpvq4c_cXu_) as the effect these textures and settings have should look more like this:

![paraocclusion](https://user-images.githubusercontent.com/45246040/58429020-1ca84c80-80ad-11e9-9de2-473ba0243d3d.png)

Should note that the material I had ingame actually had a height scale of 0.2 instead of 0.3 as the Materialize application shows but minor details, heh.

**Comment by SleepKiller** [comment]
Yup, I've definitely messed up here. Looks like I either (stupidly) made a change that broke it after I had done all my testing or it just never worked outside of very specific camera angles. Will investigate.

**Comment by SleepKiller** [comment]
As it turns out this was being caused by a typo, see here d76fbf5cb. That typo also means that normal maps for all `normal_ext` materials will have been off, I'll be posting the release containing the fix soon.
