### ISSUE TITLE
Sunflares are fixed, but suns look funny

### ISSUE THREAD

**Issue by auri0n** [SleepKiller/shaderpatch#71]
https://i.imgur.com/riWVlYJ.gifv

**Comment by SleepKiller** [comment]
I can reproduce this but only with HDR enabled, does that match your experience?

**Comment by auri0n** [comment]
nope, for me it happens without HDR :/ I'll do some more testing though

**Comment by SleepKiller** [comment]
I did more testing myself and if I reduced the exposure of the scene it also happens. Could that be what's going on for you?

**Comment by auri0n** [comment]
I doubt it, my user config is pretty bare-bones. Might be an issue with last gen nvidia graphics cards lol. I wouldn't worry too much about it, though, as it's one of the most unnoticeable "bugs" yet.
