### ISSUE TITLE
Illuminated objects in front of shadows appear to be outlined

### ISSUE THREAD

**Issue by auri0n** [SleepKiller/shaderpatch#72]
https://i.imgur.com/6J3C1kl.png

notice the top half of the player model. also, shadows aren't rendering when set to "low".

**Comment by DoctorAnsem** [comment]
I've been noticing this a lot as well. It seems to fit the description of the "HDR Halo" effect which is a very common problem when universally dealing with anything HDR, I think.

**Comment by auri0n** [comment]
interesting. Have you encountered this problem without HDR enabled? My effects config is pretty close to stock - no HDR rendering or SSAO.
