### ISSUE TITLE
Vertex colors and sRGB textures

### ISSUE THREAD

**Issue by DoctorAnsem** [SleepKiller/shaderpatch#78]
I'm guessing you might have seen this coming but as I've been using normal_ext and its subtypes to preserve the vertex coloring of models, it almost seems like there's a little bit of bad behavior when it comes to HDR and sRGB flags. When comparing a stock material side by side with a normal_ext material, there is a massive difference in the shading. As the stock material is more or less the "correct" color (as close as it can be with HDR) the normal_ext material actually goes almost pitch black in more shaded areas. I'm quite certain I've seen some note of this somewhere, something something vertex colors being forced into the wrong color space or so, but I couldn't find it and as such I couldn't figure out a convenient workaround for this.

So the big question is, can this be fixed any way at all or am I going to have to scrape off the paintwork?  :/

Alternatively, I guess I could just not use HDR in cases like this, but you know. Lights kinda suck without it.

**Comment by SleepKiller** [comment]
I may have to get back to you on this after I get the chance to do some testing. The normal and normal_ext shader both handle the vertex colors the same way (or at least are supposed to and do seem to) so I suspect something else is at play here. If I can find what is causing the difference I will do my best to fix it.

**Comment by SleepKiller** [comment]
Did some testing (finally, again sorry about the delays on a lot of these). I couldn't seam to spot any difference (with HDR rendering) between a normal_ext material with sRGB textures and vertex colors and a normal material. 

However I did spot something that could unknowingly be causing a problem with vertex colors. The StaticallyLit flag in materials can cause conflicts with models that were munged with `-vertexlighting` set. This conflicts could create problems or inconsistencies within a model. As such I have [removed](https://github.com/SleepKiller/shaderpatch/commit/fde2ac0ea7b8c190829ad4e6e22bbddbc133b4a7) the flag starting from the next release. (A bit of a radical step I know, I may roll it back if anyone thinks it was a mistake.) This is strictly a a material_munge change and as such any materials/models munged with any previous versions tools will continue to function the same as before ingame.

Not actually sure if it'll help fix your problem or not but it should remove a potential pitfall from Shader Patch's materials in any case.

**Comment by SleepKiller** [comment]
Just closing a couple old issues that I'm no longer sure how to approach looking into. This just let's me see more clearly what I do still need to look into. Feel free to reopen (or create new issues) if any of them are still having an obvious impact.
