### ISSUE TITLE
Terrain munge produces another ever-so-luminous error

### ISSUE THREAD

**Issue by DoctorAnsem** [SleepKiller/shaderpatch#82]
Don't know if this or the last one takes the lead, but this time we've got this

`Error munging RhenVar1.tmtrl: Unspecified error`

This time though, it did seem to at least try to do something because it took a few seconds longer than before, so maybe there's something in the terrain itself that it doesn't like? Although the only thing I can think of is that this terrain uses the same textures for different slots with different tile ranges and mapping directions. Could that cause such an error?

**Comment by Calrissian97** [comment]
I don't think he integrated terrain cutting yet, could that be doing it?

**Comment by SleepKiller** [comment]
Given the cryptic nature of the error I suspect it is originating from a third party library, DirectXTex would be the likely suspect still. So I'm guessing this is still texture related, I'll fuzz material_munge with some more texture scenarios and see if I can replicate it.

A sampling of the `.tex` files for your terrain could prove useful as well.

**Comment by DoctorAnsem** [comment]
Yeah so I've got them packed up [here](https://drive.google.com/open?id=1P2zDmM9PVM_MbUyaPfFfk9LKIEZHwpuc) along with the terrain material file just in case.

Regarding this,
> I don't think he integrated terrain cutting yet, could that be doing it?

I actually removed all the terrain cutters from this map ages ago (they tend to break dynamic lights on any stock terrain) so that shouldn't be possible.

**Comment by SleepKiller** [comment]
This should be fixed in the latest release, grab the updated tools and it should go away. Hopefully that's the last bug you encounter!
