### ISSUE TITLE
Built in null heightmap seems to have the wrong value

### ISSUE THREAD

**Issue by DoctorAnsem** [SleepKiller/shaderpatch#83]
Noticed when I was seeing the terrain ingame now, that the parallax occlusion made the null-heightmap textures 'slide' underneath each other. This isn't a massive issue thankfully, I've tangled with this before and resolved it with a little bit of texture work. SP's parallax occlusion simply has a different neutral point than what a lot of applications generate - SP sets the neutral point to be completely white (1.0 in brightness), in other words, it can only push pixels inward. This can be quite confusing, as it was to me at first, because some sophisticated texture tools generate height maps with a neutral point of 0.5 and treat it as such. This should probably have a note in the wiki too to avoid further confusion.

**Comment by SleepKiller** [comment]
I've updated $null_heightmap to have a value of 1.0 in the next release. I agree with your reasoning that it makes sense to have it at the point that indicates no displacement.

I have also put a note about POM displacing downwards from 1.0 in the POM section of the normal_ext documentation.
