### ISSUE TITLE
Listing up ingame problems with the new terrain

### ISSUE THREAD

**Issue by DoctorAnsem** [SleepKiller/shaderpatch#84]
So, good news, we've gotten past the munge process and terrains are now working in the game. Well, mostly. There are a few things that don't quite line up as they should, some are blatantly obvious and some are not.

1. In quite a number of cases, textures don't blend smoothly into each other, rather there's a hard edge.

2. The mapping direction that can be changed in ZE seems to be not playing very well into the new terrain. I couldn't entirely figure out what is happening but basically there are some majorly stretched textures on some steep surfaces and of course the parallax occlusion will have a spasm from this, warping the texture even further. 

3. The low res terrain might be getting reduced a bit too aggressively. I've got entire mountain tops that popped into existence out of thin air and vice versa, very much like an object that is missing low res geometry.

4. Well... then there is this:
![runtimebf2terr](https://user-images.githubusercontent.com/45246040/63108217-fea50680-bf8e-11e9-8dc2-bf571936f45c.png)
This one I have no idea wtf even happened. I'm not even 100% sure it's related to this, but it's never happened to me before so better safe than sorry. What's surprising is that this didn't happen at a sensible time at all, I had been playing this match quite a while when it just popped out of the blue. It of course didn't write anything into the log either to make this easier.

**Comment by SleepKiller** [comment]
> In quite a number of cases, textures don't blend smoothly into each other, rather there's a hard edge.

Is this with or without height maps? If it's without how hard is the edge? (I would test this myself, but I'm strapped for time atm)

> The low res terrain might be getting reduced a bit too aggressively. I've got entire mountain tops that popped into existence out of thin air and vice versa, very much like an object that is missing low res geometry.

Roger that. I went with the min filter for terrain height because otherwise terrain from the far scene could start "bleeding" over into the near scene and become visible when it shouldn't be the low res terrain wasn't contained in the silhouette of the high res terrain. A solution would be to provide the option to use the high res terrain geometry as the low res terrain for maps where it is important to maintain geometric detail in the distance.

I'll have investigate 2. in more detail since it sounds like a bug for sure. Not sure what is going on with 4. seams like quite the bug and problem, although I suspect it is unrelated to terrain. Or maybe the models I'm passing the game have too many individual segments.

**Comment by DoctorAnsem** [comment]
> Is this with or without height maps?

It was with height maps. The hardness of the edge I could best describe by what actually happens in the stock terrain too, if there are more than 3 textures layered on top of each other. Could that actually be what's happening here? I don't honestly know how many textures may be stacked in ZE, as it was always resolved automatically by including `-maxlayers 3` in the terrain's .option file.

**Comment by SleepKiller** [comment]
Maybe. I fixed quite a lot of problems like that before settling on the texture selection logic that is used. Do the hard edges form a triangle shape at places?

**Comment by DoctorAnsem** [comment]
They kind of do, and kind of don't. Sometimes it's in square shapes too. Which I guess being just two triangles makes sense.

![2019-08-17 11_51_12](https://user-images.githubusercontent.com/45246040/63209215-a84adb80-c0e6-11e9-8a73-3a958833baa2.png)

Also there are some collision inaccuracies.
![2019-08-17 11_50_06](https://user-images.githubusercontent.com/45246040/63209222-b3057080-c0e6-11e9-9cfd-59b5082da12f.png)

Furthermore I actually saw parts of the low res terrain ghosting in the near scene just now.

**Comment by DoctorAnsem** [comment]
Uh. You might want to take a look at [this.](https://drive.google.com/open?id=1NfIDm78H_NByH0n_mDArQwGQrutV_vRa) There's something that has gone horribly wrong with the geometry alignment here, I don't even know how to properly describe it. 

Also larger than default terrains don't seem to work. It will munge without issues (although it takes a while) but the game will just freeze during the load screen.

**Comment by DoctorAnsem** [comment]
Just got another one of these horrendously buggy terrains. Both of these have happened with PBR terrains specifically so I guess that's something to look at. It also looks like only one PBR material gets included in the terrain, the rest are ignored.

**Comment by SleepKiller** [comment]
Save the issues with parallax mapping (#91) and the alignment (which I haven't been able to replicate as of yet, but I have created a separate issue to track it #92) these should hopefully all be fixed in the upcoming release.
