### ISSUE TITLE
RGBA Vertex colors.

### ISSUE THREAD

**Issue by DoctorAnsem** [SleepKiller/shaderpatch#87]
Somehow this hasn't been an issue until now, until one obscure thing uses it intuitively and I guess for a most logical purpose. So the word is, at least `basic_unlit` is going to need support for vertex color alpha, otherwise planets in skydomes can't smoothly blend between light and dark textures. :(

![2019-08-28 22_09_13](https://user-images.githubusercontent.com/45246040/63885478-1fcf1380-c9e1-11e9-85c0-4e8e1fd4c5b7.png)

**Comment by SleepKiller** [comment]
Pretty simple update, will add to the next release.
