### ISSUE TITLE
Particles seem kind of faded again

### ISSUE THREAD

**Issue by DoctorAnsem** [SleepKiller/shaderpatch#95]
I'm not sure if it's as obvious as the last time, but there is some sort of a change in how particles look now. Or maybe I should say, how they _don't_ look.

**Comment by SleepKiller** [comment]
Is this specific to when HDR rendering is enabled or is it just in general?

**Comment by DoctorAnsem** [comment]
It's just HDR, I think.

**Comment by DoctorAnsem** [comment]
You know what? Maybe I was wrong about this one. I did some comparisons and the stock shaders, with SP completely disabled, they aren't any better really. The particles were apparently always that way on PC - maybe at some point SP had drawn them more prominently and that's why I got confused when they aren't so vibrant and bright anymore. At any rate, this might just be a non-issue.

**Comment by SleepKiller** [comment]
May as well close this then. Just reopen it or a new issue if it ever does turn out to be an issue.
